# Generated by Django 3.1.5 on 2021-02-25 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tarifa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6)),
                ('descripcion', models.CharField(max_length=120)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ficharegistral', models.CharField(max_length=12)),
                ('nombres', models.CharField(max_length=120)),
                ('dni', models.IntegerField()),
                ('observaciones', models.CharField(max_length=150)),
                ('hojaremision', models.CharField(max_length=16)),
                ('estado', models.CharField(choices=[('R', 'Registrado'), ('E', 'Enviado'), ('R', 'Recibido'), ('X', 'Entregado')], max_length=1)),
                ('tarifa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.tarifa')),
            ],
        ),
    ]
