# Generated by Django 3.1.5 on 2021-02-27 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20210226_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='docs_adjuntos',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
