# Generated by Django 3.1.5 on 2021-03-21 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_application_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='estado',
            field=models.CharField(choices=[('R', 'Registrado'), ('E', 'Enviado'), ('O', 'Recibido'), ('X', 'Entregado')], max_length=1),
        ),
    ]
